required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"

[[override]]
  name = "k8s.io/gengo"
  revision = "b6c426f7730e6d66e6e476a85d1c3eb7633880e0"
