apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nodeset-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-node
        controller: nodeset
    spec:
      volumes:
      - name: gcp-account
        secret:
          secretName: nodeset-gcloud-service-account
      containers:
      - name: controller
        image: kubenode/nodeset-controller:latest
        command:
        - /nodeset-controller
        args:
        - --backend=gke
        - --gke-cluster-id=CLUSTER
        - --gke-project-id=PROJECT_ID
        - --gke-zone=ZONE
        - --logtostderr
        - --v=5
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: gcp-account
          readOnly: true
          mountPath: "/etc/gcp"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/gcp/secret.json"
